language: ruby
sudo: false

notifications:
  email: false

matrix:
  include:
    - rvm: 2.7.1
      env: "RAILS_VERSION=6.0.3.2"
    - rvm: 2.6.6
      env: "RAILS_VERSION=6.0.3.2"
    - rvm: 2.6.6
      env: "RAILS_VERSION=5.2.4.3"

before_install:
  - gem install bundler

notifications:
  irc: "irc.freenode.org#blacklight"
  email:
      - blacklight-commits@googlegroups.com

global_env:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

jdk: openjdk11
